name: Deploy to Cloudflare

on:
  push:
    branches:
      - main
      - dev
    paths:
      - .github/workflows/deoply.yml
      - package.json
      - public/**
      - src/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - run: |
          if [[ -n "${{ vars.SITE_NAME }}" ]]; then
            sed -i "s#SiteName: .*#SiteName: '${{ vars.SITE_NAME }}',#" public/config.js
          fi
          if [[ -n "${{ vars.API_KEYS }}" ]]; then
            formatted=$(echo "${{ vars.API_KEYS }}" | sed 's/,/\n/g' | sed "s/^/'/g" | sed "s/$/',/g" | tr '\n' ' ')
            sed -i "/ApiKeys: \[/a \\$formatted" public/config.js
          fi
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          packageManager: yarn
          preCommands: |
            yarn install
            yarn build
          command: |
            pages deploy ./build --project-name=${{ vars.PROJECT_NAME || 'status' }}
