name: Deploy

on:
  push:
    branches:
      - main
      - dev
    paths:
      - .github/workflows/deoply.yml
      - package.json
      - public/**
      - src/**

  workflow_dispatch:
    inputs:
      environment:
        description: "Choose an environment to deploy to: <dev|staging|prod|main>"
        required: true
        default: "dev"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set config.js
        run: |
          if [[ -n "${{ vars.SITE_NAME }}" ]]; then
            sed -i "s#SiteName: .*#SiteName: '${{ vars.SITE_NAME }}',#" public/config.js
          fi
          if [[ -n "${{ vars.API_KEYS }}" ]]; then
            formatted=$(echo "${{ vars.API_KEYS }}" | sed 's/,/\n/g' | sed "s/^/'/g" | sed "s/$/',/g" | tr '\n' ' ')
            sed -i "/ApiKeys: \[/a \\$formatted" public/config.js
          fi
          if [[ -n "${{ vars.COUNT_DAYS }}" ]]; then
            sed -i "s#CountDays: .*#CountDays: ${{ vars.COUNT_DAYS }},#" public/config.js
          fi
          if [[ -n "${{ vars.SHOW_LINK }}" ]]; then
            sed -i "s#ShowLink: .*#ShowLink: ${{ vars.SHOW_LINK }},#" public/config.js
          fi
          if [[ -n "${{ vars.NAV_ITEMS }}" ]]; then
            echo "${{ vars.NAV_ITEMS }}" > content.txt
            sed '/Navi: \[/r content.txt' public/config.js > temp.txt
            mv temp.txt public/config.js
          fi
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  cloudflare:
    runs-on: ubuntu-latest
    needs: build
    env:
      BRANCH: ${{ inputs.BRANCH != '' && inputs.BRANCH || vars.BRANCH }}
    steps:      
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages   
          path: build    
      - name: Extract artifact
        run: |
          mkdir -p dist
          tar -xvf build/*.tar -C dist
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: |
            pages deploy dist --project-name=${{ vars.PROJECT_NAME || 'status' }} --branch=${{ vars.BRANCH || 'main' }}

  # Deployment job
  deploy:
    environment:
      name: pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4